apiVersion: v1
stringData:
  MYSQL_URL: "mysql://socialflow_dev:b7mw-NFF0zIRuv8DIi@gznoneprodmysql.internal.cn-south-1.mysql.rds.myhuaweicloud.com:3306/socialflow_main_dev"
  REDIS_DB: '218'
  REDIS_PWD: "wvMn4OBlhXuCJ68VK"
  REDIS_URL: "redis://redis-c44f43bd-58c3-4908-92c1-8e3b3f19dfe1e.cn-south-1.dcs.myhuaweicloud.com:6379"
  MONGO_URL: "mongodb://socialflow_dev:VNKfUAKO2eWGle26V8RiB@172.21.3.212:8635,172.21.3.52:8635/socialflow_eventlog_dev?replicaSet=replica&authSource=admin"
  MONGO_DATABASE: "socialflow_eventlog_dev"
  # 静态存储服务 cos, s3, tos, obs
  STORAGE_PROVIDER: "obs"
  # 对象存储配置
  STORAGE_BUCKET_ENDPOINT: "obs.cn-south-1.myhuaweicloud.com"
  STORAGE_PUBLIC_BUCKET_ENDPOINT: "obs.cn-south-1.myhuaweicloud.com"
  STORAGE_PUBLIC_BUCKET_HOST: "https://soflow-public.obs.cn-south-1.myhuaweicloud.com"
  STORAGE_REGION: "cn-south-1"
  STORAGE_BUCKET: "soflow-qa-private"
  STORAGE_PUBLIC_BUCKET: "soflow-qa-public"
  STORAGE_ACCESS_KEY_ID: "FQNVAXSW6I5OMNFSZV2L"
  STORAGE_SECRET_ACCESS_KEY: "TV6Ad4r4P6KBs8ZEhfDjtCaxV32YsMlB1DKRbLo2"
  # Pulsar
  PULSAR_SERVICE_URL: ""
  PULSAR_TOKEN: ""
  PULSAR_OPERATION_TIMEOUT_SECONDS: ""
  DEFAULT_CONSUMER_SUBSCRIPTION: ""
  PULSAR_NAMESPACE: ""
  PULSAR_CLUSTER: ""
  # UC
  UC_ENDPOINT: "http://uc-server.socialflow.svc.cluster.local"
kind: Secret
metadata:
  name: cm-main
  namespace: social-x-main-dev
type: Opaque