kind: Service
apiVersion: v1
metadata:
  name: main
  namespace: social-x-main-dev
spec:
  selector:
    app: main
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
