apiVersion: v1
stringData:
  MYSQL_URL: ""
  REDIS_DB: ''
  REDIS_PWD: ""
  REDIS_URL: ""
  MONGO_URL: ""
  MONGO_DATABASE: ""
  # 静态存储服务 cos, s3, tos, obs
  STORAGE_PROVIDER: "tos"
  # 对象存储配置
  STORAGE_BUCKET_ENDPOINT: ""
  STORAGE_PUBLIC_BUCKET_ENDPOINT: ""
  STORAGE_PUBLIC_BUCKET_HOST: ""
  STORAGE_REGION: ""
  STORAGE_BUCKET: ""
  STORAGE_PUBLIC_BUCKET: ""
  STORAGE_ACCESS_KEY_ID: ""
  STORAGE_SECRET_ACCESS_KEY: ""
  # Pulsar
  PULSAR_SERVICE_URL: ""
  PULSAR_TOKEN: ""
  PULSAR_OPERATION_TIMEOUT_SECONDS: ""
  DEFAULT_CONSUMER_SUBSCRIPTION: ""
  PULSAR_NAMESPACE: ""
  PULSAR_CLUSTER: ""
  # UC
  UC_ENDPOINT: "http://uc-server"
  # trace 配置
  IS_TRACE_ON: "0"
  TRACE_GRPC_ENDPOINT: ""
  TRACE_APP_KEY: ""
  TRACE_SERVICE_NAME: ""
kind: Secret
metadata:
  name: cm-main
  namespace: social-x-main
type: Opaque